import {User} from "../user";

export interface SubComment {
    _id?: {
        $oid: string
    };
    commenter: User;
    quotedSnippet?: string; //generated by highlighting abstract... may not always be needed
    commenterInput: string;
    resolved?: boolean; //Top level comments (TLC's) resolvable, comments on TLC resolved via TLC resolution
    timestamp: string;
}

export interface TopComment extends SubComment {
    subComments: Array<SubComment>;
}
